### ISSUE TITLE
When shulker box is stackable，it can be used to copy items

### ISSUE THREAD

**Issue by xiaoyan2007** [RealMegaMinds/ClickOpener#12]
When shulker box is stackable，it can be used to copy items
When shulker box is stackable, Open the stacked boxes and put something into it
Then put every box down, and found the every box have that item

**Comment by Ultimushadow** [comment]
Since shulkers are the only block that store items, I can see that the class called takes an itemStack, if you use a check with .getAmount() you could filter out whether or not the box is stacked? And then you could do something like send a message in chat saying stacked inventories can't be opened. I was also going to use a mod which allowed empty shulker boxes to be stacked so I would definitely be interested in a fix, also this would be a good thing to implement if you expand your mod compats to include other BlockItems that may or may not be able to be stacked!

**Comment by Hoid2** [comment]
This should have been fixed in version 2.0.6+1.20.1 and later

**Comment by Hoid2** [comment]
I am going to close this. If you find it is still an issue, you can reopen but let me know the version.
